In [18]:
# Understanding Numpy 
# Numpy used to dealing with all arrays(including multidimenssional arrays) and it is Base layer to implement any algorithm
# Internal implementation of numpy is float
# Internal working structure of an array
# : Vectors for processing the code -- faster execution
# : Better implementation of indexing - faster retrieval
# Howto install numpy

In [2]:
! pip install numpy

In [17]:
! pip install numpy --upgrade

Requirement already up-to-date: numpy in c:\users\sairam\anaconda3\lib\site-packages (1.18.2)


In [4]:
# How to import this library

In [6]:
import numpy as np

In [7]:
array_one=np.array([1,2,3,4,5])
array_one

array([1, 2, 3, 4, 5])

In [8]:
type(array_one)

numpy.ndarray

In [9]:
money_spent_in_dollars=[5,8,4,90]

In [10]:
array_two=np.array(money_spent_in_dollars)

In [11]:
array_two

array([ 5,  8,  4, 90])

In [13]:
# create an array of zeros with desired shape(x,y)
# x- number of rows y- number of cols
# array of zeros is used to create dummy data

In [14]:
array_of_zeros=np.zeros((3,4))

In [15]:
array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# What is the diff b/w list and numpy array? what do u prefer?
# array is most prefered.
# LLIst and array - same feaures in way of indexing and calling out
# but the specification of array is better. why?